name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  FORCE_COLOR: 3

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Create Release PR or Publish Packages
        id: changesets
        uses: changesets/action@v1.4.1
        with:
          # Builds the package and executes `changeset publish`
          publish: pnpm release
          # Alias to `changeset version` script in package.json
          version: pnpm version-packages
          commit: 'chore: update package versions'
          title: 'chore: update package versions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send a Discord notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"content":"A new version of the package has been published!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
